adopted release script for CTAN package browsing policies

diff --git a/scripts/pgfplots/Makefile.pgfplots_release_sourceforge b/scripts/pgfplots/Makefile.pgfplots_release_sourceforge
--- a/scripts/pgfplots/Makefile.pgfplots_release_sourceforge
+++ b/scripts/pgfplots/Makefile.pgfplots_release_sourceforge
@@ -42,14 +42,25 @@ FORCE:
 
 ctanzip: $(CTANZIP)
 
+# code to satisfy http://www.ctan.org/upload ...
 $(CTANZIP): $(ZIP)
 	rm -fr /tmp/pgfplots /tmp/pgfplots.ctan.tmp $@
 	mkdir -p /tmp/pgfplots /tmp/pgfplots.ctan.tmp
 	cd /tmp/pgfplots.ctan.tmp && unzip $(abspath $(ZIP))
 	mv /tmp/pgfplots.ctan.tmp/doc/latex/pgfplots /tmp/pgfplots/doc
+	mv /tmp/pgfplots.ctan.tmp/doc/generic/pgfplots/README /tmp/pgfplots
+	cp $(ZIP) /tmp/pgfplots.tds.zip
+	mkdir /tmp/pgfplots/tex
+	mkdir /tmp/pgfplots/source
+	mkdir /tmp/pgfplots/scripts
+	find /tmp/pgfplots.ctan.tmp/tex -type f -exec mv -i {} /tmp/pgfplots/tex \;
+	find /tmp/pgfplots.ctan.tmp/source -type f -exec mv -i {} /tmp/pgfplots/source \;
+	find /tmp/pgfplots.ctan.tmp/scripts -type f -exec mv -i {} /tmp/pgfplots/scripts \;
+	find /tmp/pgfplots.ctan.tmp/doc -type f -exec mv -i {} /tmp/pgfplots/doc \;
 	echo "Please search for pgfplots.tds.zip and install that one into a local texmf branch (which is typically simpler). This release is intended to satisfy CTAN package browsing policies." > /tmp/pgfplots/INSTALL
-	find /tmp/pgfplots.ctan.tmp -type f -exec cp -i {} /tmp/pgfplots \;
-	cd /tmp && zip -r $(abspath $@) pgfplots
+	@NUM_FILES=$$(find /tmp/pgfplots.ctan.tmp/ -type f |wc -l); \
+	if [ $$NUM_FILES -gt 0 ]; then echo "INTERNAL FAILURE: $$NUM_FILES FILES LEFT OVER IN /tmp/pgfplots.ctan.tmp! All must be included into $@. Left-overs:"; find /tmp/pgfplots.ctan.tmp/ -type f; exit 1; fi
+	cd /tmp && zip -r $(abspath $@) pgfplots pgfplots.tds.zip
 
 
 $(ZIP): FORCE
@@ -85,6 +96,7 @@ $(ZIP): FORCE
 		--exclude='pgfplotstable.example1.out.*' \
 		--exclude='source/latex/pgfplots/pgfplotstest/unittests/references' \
 		--exclude='doc/latex/pgfplots/bugtracker' \
+		--exclude='P.sh' \
 		--exclude='*.diff' \
 		--exclude='expensiveexample*' \
 		--exclude='Makefile.pgfplots_release_sourceforge' \
